import React, { useState } from 'react';
import { FileText, List, BookOpen, HelpCircle, Download, Copy, Check, Share2, MessageCircle, Mail, Twitter } from 'lucide-react';

const ResultDisplay = ({ results, loading }) => {
  const [copied, setCopied] = useState('');

  const copyToClipboard = async (text, type) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(''), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  const downloadAsText = (content, filename) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const shareViaWhatsApp = (content) => {
    const text = encodeURIComponent(content.substring(0, 1000) + '...\n\nGenerated by Book Summarizer AI');
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const shareViaEmail = (content, title) => {
    const subject = encodeURIComponent(`${title} - Book Summarizer AI`);
    const body = encodeURIComponent(content + '\n\nGenerated by Book Summarizer AI');
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
  };

  const shareViaTwitter = (content, title) => {
    const text = encodeURIComponent(`${title}: ${content.substring(0, 200)}...\n\n#AI #BookSummarizer`);
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
  };

  const formatFlashcards = (flashcards) => {
    if (!flashcards) return '';
    
    const cards = flashcards.split('\n\n').filter(card => card.trim());
    return cards.map((card, index) => {
      const lines = card.split('\n').filter(line => line.trim());
      const questionLine = lines.find(line => line.toLowerCase().includes('q:')) || lines.find(line => line.toLowerCase().includes('question:'));
      const answerLine = lines.find(line => line.toLowerCase().includes('a:')) || lines.find(line => line.toLowerCase().includes('answer:'));
      
      const question = questionLine ? questionLine.replace(/^(q:|question:)/i, '').trim() : `Question ${index + 1}`;
      const answer = answerLine ? answerLine.replace(/^(a:|answer:)/i, '').trim() : 'Answer not found';
      
      return { question, answer };
    });
  };

  const formatQA = (qa) => {
    if (!qa) return '';
    
    // Split by numbered question patterns
    const questions = [];
    const questionBlocks = qa.split(/^\d+\./m).filter(block => block.trim());
    
    questionBlocks.forEach((block, index) => {
      const lines = block.split('\n').filter(line => line.trim());
      
      let question = '';
      let answer = '';
      let isAnswer = false;
      
      for (const line of lines) {
        if (line.match(/^[A-D]\)/)) {
          // This is a multiple choice option, add to question
          question += '\n' + line;
        } else if (line.toLowerCase().includes('answer:') || line.toLowerCase().includes('answer:')) {
          isAnswer = true;
          answer = line.replace(/\*\*answer:\*\*/i, '').replace(/answer:/i, '').trim();
        } else if (isAnswer && line.trim()) {
          answer += ' ' + line;
        } else if (!isAnswer && line.trim()) {
          // This is the question part
          question = question + (question ? ' ' : '') + line;
        }
      }
      
      if (question) {
        questions.push({ 
          question: question.trim(),
          answer: answer || 'Answer not available' 
        });
      }
    });
    
    return questions;
  };

  const sections = [
    {
      id: 'summary',
      title: 'Summary',
      icon: FileText,
      content: results.summary,
      loading: loading.summary,
      color: 'blue',
      hasActions: true
    },
    {
      id: 'keyPoints',
      title: 'Key Points',
      icon: List,
      content: results.keyPoints,
      loading: loading.keyPoints,
      color: 'green',
      hasActions: true
    },
    {
      id: 'flashcards',
      title: 'Flashcards',
      icon: BookOpen,
      content: results.flashcards,
      loading: loading.flashcards,
      color: 'purple',
      hasActions: true,
      specialFormat: 'flashcards'
    },
    {
      id: 'qa',
      title: 'Questions & Answers',
      icon: HelpCircle,
      content: results.qa,
      loading: loading.qa,
      color: 'orange',
      hasActions: true,
      specialFormat: 'qa'
    }
  ];

  const getColorClasses = (color) => {
    const colors = {
      blue: {
        bg: 'bg-blue-50',
        border: 'border-blue-200',
        text: 'text-blue-800',
        icon: 'text-blue-600'
      },
      green: {
        bg: 'bg-green-50',
        border: 'border-green-200',
        text: 'text-green-800',
        icon: 'text-green-600'
      },
      purple: {
        bg: 'bg-purple-50',
        border: 'border-purple-200',
        text: 'text-purple-800',
        icon: 'text-purple-600'
      },
      orange: {
        bg: 'bg-orange-50',
        border: 'border-orange-200',
        text: 'text-orange-800',
        icon: 'text-orange-600'
      }
    };
    return colors[color] || colors.blue;
  };

  const formatContent = (content) => {
    let formattedContent = content;
    
    // Enhanced formatting for better alignment and structure
    formattedContent = formattedContent.replace(/\*\*Main Objective:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Main Objective</h3>');
    formattedContent = formattedContent.replace(/\*\*Key Concepts:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Key Concepts</h3>');
    formattedContent = formattedContent.replace(/\*\*Implementation:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Implementation</h3>');
    formattedContent = formattedContent.replace(/\*\*Applications\/Conclusion:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Applications & Conclusion</h3>');
    formattedContent = formattedContent.replace(/\*\*Introduction:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Introduction</h3>');
    formattedContent = formattedContent.replace(/\*\*Core Concepts:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Core Concepts</h3>');
    formattedContent = formattedContent.replace(/\*\*Technical Details:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Technical Details</h3>');
    formattedContent = formattedContent.replace(/\*\*Real-world Applications:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Real-world Applications</h3>');
    formattedContent = formattedContent.replace(/\*\*Conclusion:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Conclusion</h3>');
    formattedContent = formattedContent.replace(/\*\*Main Points:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Main Points</h3>');
    formattedContent = formattedContent.replace(/\*\*Key Points:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Key Points</h3>');
    formattedContent = formattedContent.replace(/\*\*Applications:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Applications</h3>');
    formattedContent = formattedContent.replace(/\*\*Types of Learning:\*\*/g, '<h3 class="text-xl font-bold text-gray-900 mb-4">Types of Learning</h3>');
    
    // Enhanced bullet point formatting with better alignment
    formattedContent = formattedContent.replace(/^- \*\*(.+?):\*\*/g, '<li class="ml-6 mb-3 font-semibold text-gray-800"><span class="text-gray-700">$1</span></li>');
    formattedContent = formattedContent.replace(/^- (.+)/g, '<li class="ml-6 mb-2">$1</li>');
    formattedContent = formattedContent.replace(/•\s+(.+)/g, '<li class="ml-6 mb-2">$1</li>');
    
    // Better line breaks and spacing
    formattedContent = formattedContent.replace(/\n\n/g, '<br /><br />');
    formattedContent = formattedContent.replace(/\n/g, '<br />');
    
    return formattedContent;
  };

  return (
    <div className="space-y-6">
      {sections.map((section) => {
        const Icon = section.icon;
        const colors = getColorClasses(section.color);
        const hasContent = section.content && !section.loading;

        return (
          <div
            key={section.id}
            className={`card border-2 transition-all duration-300 ${
              hasContent ? `${colors.bg} ${colors.border}` : 'border-gray-200'
            }`}
          >
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-3">
                <div className={`p-2 rounded-lg ${colors.bg}`}>
                  <Icon className={`w-5 h-5 ${colors.icon}`} />
                </div>
                <h3 className="text-lg font-semibold text-gray-900">{section.title}</h3>
              </div>
              
              {hasContent && section.hasActions && (
                <div className="flex space-x-2">
                  <button
                    onClick={() => copyToClipboard(section.content, section.id)}
                    className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                    title="Copy to clipboard"
                  >
                    {copied === section.id ? (
                      <Check className="w-4 h-4" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                  <button
                    onClick={() => downloadAsText(section.content, `${section.title.toLowerCase().replace(' ', '_')}.txt`)}
                    className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                    title="Download as text file"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                  <div className="relative group">
                    <button
                      className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                      title="Share"
                    >
                      <Share2 className="w-4 h-4" />
                    </button>
                    <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-10">
                      <button
                        onClick={() => shareViaWhatsApp(section.content)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-t-lg"
                      >
                        <MessageCircle className="w-4 h-4 mr-2 text-green-600" />
                        WhatsApp
                      </button>
                      <button
                        onClick={() => shareViaEmail(section.content, section.title)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        <Mail className="w-4 h-4 mr-2 text-blue-600" />
                        Email
                      </button>
                      <button
                        onClick={() => shareViaTwitter(section.content, section.title)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-b-lg"
                      >
                        <Twitter className="w-4 h-4 mr-2 text-sky-500" />
                        Twitter
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {section.loading && (
              <div className="flex items-center justify-center py-8">
                <div className="loading-spinner mr-3"></div>
                <span className={`${colors.text} font-medium`}>Generating {section.title.toLowerCase()}...</span>
              </div>
            )}

            {!section.content && !section.loading && (
              <div className="text-center py-8 text-gray-500">
                <Icon className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p>No {section.title.toLowerCase()} generated yet</p>
                <p className="text-sm mt-2">Click the button above to generate {section.title.toLowerCase()}</p>
              </div>
            )}

            {section.content && !section.loading && (
              <div className="animate-fade-in">
                {section.specialFormat === 'flashcards' ? (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {formatFlashcards(section.content).map((card, index) => (
                      <div key={index} className="bg-white p-6 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                        <div className="font-medium text-blue-700 mb-3">
                          <span className="text-sm text-blue-500 font-semibold">Q:</span> {card.question}
                        </div>
                        <div className="text-gray-700 leading-relaxed">
                          <span className="text-sm text-green-600 font-semibold">A:</span> {card.answer}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : section.specialFormat === 'qa' ? (
                  <div className="space-y-8">
                    {formatQA(section.content).map((pair, index) => (
                      <div key={index} className="bg-white p-8 rounded-xl border border-gray-200 shadow-md hover:shadow-lg transition-shadow">
                        <div className="mb-6">
                          <div className="flex items-center mb-4">
                            <span className="bg-blue-100 text-blue-800 text-sm font-semibold px-3 py-1 rounded-full mr-3">
                              Question {index + 1}
                            </span>
                            <span className="text-sm text-gray-500">
                              {pair.question.includes('Multiple Choice') ? 'Multiple Choice' : 
                               pair.question.includes('Short Answer') ? 'Short Answer' : 'Essay'}
                            </span>
                          </div>
                          <div className="text-lg font-semibold text-gray-900 leading-relaxed whitespace-pre-line">
                            {pair.question}
                          </div>
                        </div>
                        <div className="border-t border-gray-200 pt-6">
                          <div className="flex items-center mb-3">
                            <span className="bg-green-100 text-green-800 text-sm font-semibold px-3 py-1 rounded-full">
                              Answer
                            </span>
                          </div>
                          <div className="text-gray-700 leading-relaxed whitespace-pre-line">
                            {pair.answer}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className={`prose prose-lg max-w-none ${colors.text} leading-relaxed`} dangerouslySetInnerHTML={{ __html: formatContent(section.content) }} />
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default ResultDisplay;
