import React, { useState } from 'react';
import { FileText, List, BookOpen, HelpCircle, Download, Copy, Check, Share2, MessageCircle, Mail, Twitter } from 'lucide-react';

const ResultDisplay = ({ results, loading }) => {
  const [copied, setCopied] = useState('');

  const copyToClipboard = async (text, type) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(''), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  const downloadAsText = (content, filename) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const shareViaWhatsApp = (content) => {
    const text = encodeURIComponent(content.substring(0, 1000) + '...\n\nGenerated by Book Summarizer AI');
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const shareViaEmail = (content, title) => {
    const subject = encodeURIComponent(`${title} - Book Summarizer AI`);
    const body = encodeURIComponent(content + '\n\nGenerated by Book Summarizer AI');
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
  };

  const shareViaTwitter = (content, title) => {
    const text = encodeURIComponent(`${title}: ${content.substring(0, 200)}...\n\n#AI #BookSummarizer`);
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
  };

  const formatFlashcards = (flashcards) => {
    if (!flashcards) return '';
    
    const cards = flashcards.split('\n\n').filter(card => card.trim());
    return cards.map((card, index) => {
      const lines = card.split('\n').filter(line => line.trim());
      const question = lines.find(line => line.toLowerCase().includes('question:'))?.replace('Question:', '').trim() || `Question ${index + 1}`;
      const answer = lines.find(line => line.toLowerCase().includes('answer:'))?.replace('Answer:', '').trim() || 'Answer not found';
      return { question, answer };
    });
  };

  const formatQA = (qa) => {
    if (!qa) return '';
    
    const pairs = qa.split('\n\n').filter(pair => pair.trim());
    return pairs.map((pair, index) => {
      const lines = pair.split('\n').filter(line => line.trim());
      const question = lines[0]?.trim() || `Question ${index + 1}`;
      const answer = lines.slice(1).join(' ').trim() || 'Answer not found';
      return { question, answer };
    });
  };

  const sections = [
    {
      id: 'summary',
      title: 'Summary',
      icon: FileText,
      content: results.summary,
      loading: loading.summary,
      color: 'blue',
      hasActions: true
    },
    {
      id: 'keyPoints',
      title: 'Key Points',
      icon: List,
      content: results.keyPoints,
      loading: loading.keyPoints,
      color: 'green',
      hasActions: true
    },
    {
      id: 'flashcards',
      title: 'Flashcards',
      icon: BookOpen,
      content: results.flashcards,
      loading: loading.flashcards,
      color: 'purple',
      hasActions: true,
      specialFormat: 'flashcards'
    },
    {
      id: 'qa',
      title: 'Questions & Answers',
      icon: HelpCircle,
      content: results.qa,
      loading: loading.qa,
      color: 'orange',
      hasActions: true,
      specialFormat: 'qa'
    }
  ];

  const getColorClasses = (color) => {
    const colors = {
      blue: {
        bg: 'bg-blue-50',
        border: 'border-blue-200',
        text: 'text-blue-800',
        icon: 'text-blue-600'
      },
      green: {
        bg: 'bg-green-50',
        border: 'border-green-200',
        text: 'text-green-800',
        icon: 'text-green-600'
      },
      purple: {
        bg: 'bg-purple-50',
        border: 'border-purple-200',
        text: 'text-purple-800',
        icon: 'text-purple-600'
      },
      orange: {
        bg: 'bg-orange-50',
        border: 'border-orange-200',
        text: 'text-orange-800',
        icon: 'text-orange-600'
      }
    };
    return colors[color] || colors.blue;
  };

  return (
    <div className="space-y-6">
      {sections.map((section) => {
        const Icon = section.icon;
        const colors = getColorClasses(section.color);
        const hasContent = section.content && !section.loading;

        return (
          <div
            key={section.id}
            className={`card border-2 transition-all duration-300 ${
              hasContent ? `${colors.bg} ${colors.border}` : 'border-gray-200'
            }`}
          >
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-3">
                <div className={`p-2 rounded-lg ${colors.bg}`}>
                  <Icon className={`w-5 h-5 ${colors.icon}`} />
                </div>
                <h3 className="text-lg font-semibold text-gray-900">{section.title}</h3>
              </div>
              
              {hasContent && section.hasActions && (
                <div className="flex space-x-2">
                  <button
                    onClick={() => copyToClipboard(section.content, section.id)}
                    className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                    title="Copy to clipboard"
                  >
                    {copied === section.id ? (
                      <Check className="w-4 h-4" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                  <button
                    onClick={() => downloadAsText(section.content, `${section.title.toLowerCase().replace(' ', '_')}.txt`)}
                    className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                    title="Download as text file"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                  <div className="relative group">
                    <button
                      className={`p-2 rounded-lg ${colors.bg} ${colors.icon} hover:opacity-80 transition-opacity`}
                      title="Share"
                    >
                      <Share2 className="w-4 h-4" />
                    </button>
                    <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-10">
                      <button
                        onClick={() => shareViaWhatsApp(section.content)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-t-lg"
                      >
                        <MessageCircle className="w-4 h-4 mr-2 text-green-600" />
                        WhatsApp
                      </button>
                      <button
                        onClick={() => shareViaEmail(section.content, section.title)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      >
                        <Mail className="w-4 h-4 mr-2 text-blue-600" />
                        Email
                      </button>
                      <button
                        onClick={() => shareViaTwitter(section.content, section.title)}
                        className="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-b-lg"
                      >
                        <Twitter className="w-4 h-4 mr-2 text-sky-500" />
                        Twitter
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {section.loading && (
              <div className="flex items-center justify-center py-8">
                <div className="loading-spinner mr-3"></div>
                <span className={`${colors.text} font-medium`}>Generating {section.title.toLowerCase()}...</span>
              </div>
            )}

            {!section.content && !section.loading && (
              <div className="text-center py-8 text-gray-500">
                <Icon className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p>No {section.title.toLowerCase()} generated yet</p>
                <p className="text-sm mt-2">Click the button above to generate {section.title.toLowerCase()}</p>
              </div>
            )}

            {section.content && !section.loading && (
              <div className="animate-fade-in">
                {section.specialFormat === 'flashcards' ? (
                  <div className="space-y-4">
                    {formatFlashcards(section.content).map((card, index) => (
                      <div key={index} className="bg-white p-4 rounded-lg border border-gray-200">
                        <div className="font-medium text-gray-900 mb-2">
                          Q: {card.question}
                        </div>
                        <div className="text-gray-700">
                          A: {card.answer}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : section.specialFormat === 'qa' ? (
                  <div className="space-y-4">
                    {formatQA(section.content).map((pair, index) => (
                      <div key={index} className="bg-white p-4 rounded-lg border border-gray-200">
                        <div className="font-medium text-gray-900 mb-2">
                          Q{index + 1}: {pair.question}
                        </div>
                        <div className="text-gray-700">
                          A: {pair.answer}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className={`whitespace-pre-wrap ${colors.text} leading-relaxed`}>
                    {section.content}
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default ResultDisplay;
